# Docker compose to develop
version: "3"
services:
  backend:
    image: kriive/kurento-backend:latest
    environment:
      - KMS_ADDR
      - KMS_PORT
    ports:
      - "8082"
  frontend:
    image: kriive/kurento-frontend:latest
    environment:
      - NGINX_PORT=4200
      - NGINX_HOST=$HOSTNAME
    ports:
      - "4200"
    links:
      - backend
